officemgmt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['namespace'=>'backend'],function(){
  Route::get('/', 'DashboardController@getLogin');

  Route::get('admin', 'DashboardController@getLogin');
  Route::post('admin', 'DashboardController@postLogin');
  Route::get('admin/logout', 'DashboardController@getLogout');

  Route::get('admin/{user_id}/dashboard','DashboardController@index');
  Route::get('admin/dashboard','DashboardController@index');
  Route::resource('admin/user','UserController');
  
  Route::resource('admin/user','UserController');
  Route::post('admin/json','JsonController@json');
  Route::resource('admin/service_charge','ServiceChargeController');


  Route::resource('admin/cash_in','cash_inController');

  Route::resource('admin/cash_out','CashOutController');

  Route::resource('admin/DHA','DHAController');
  Route::resource('admin/enquiry','EnquiryController');
  Route::resource('admin/enquirybythem','EnquiryByThemController');
  Route::resource('admin/enquiryinoffice','EnquiryInOFficeController');
  Route::resource('admin/invoice','InvoiceController');
  Route::resource('admin/reminder','ReminderController');
  Route::resource('admin/service','ServiceController');
  Route::resource('admin/student','StudentController');
  Route::resource('admin/transaction','TransactionController');
  Route::resource('admin/offer','OfferController');
  Route::resource('admin/status','StatusController');
  Route::get('admin/dhastatus','StatusController@createdhastatus');
  Route::post('admin/dhastatus','StatusController@postdhastatus');
  Route::resource('admin/dataflow','DataFlowStatusController');
  Route::get('admin/dataflowform','DataFlowStatusController@create');
  Route::post('admin/dataflowform','DataFlowStatusController@store');
  Route::post('admin/contact','OfferController@postOffer');

  Route::resource('admin/examstatus','ExamStatusController');
  Route::get('admin/examstatusform','ExamStatusController@create');
  Route::post('admin/examstatusform','ExamStatusController@store');
    // newsletter
  Route::get('admin/news','NewsLetterController@contact');
  Route::post('admin/news','NewsLetterController@postcontact');
    // CMS
  Route::get('admin/cms','cmsController@index');
  Route::get('updatePassword', 'DashboardController@updatePassword');   
  Route::get('admin/{username}/profile', 'DashboardController@profile');        
  Route::post('/profilepost', 'DashboardController@updatePassword')->name('profilepost');
  Route::post('/profilepost/{id}', 'DashboardController@editInfo');
  Route::post('updateProfile','DashboardController@updateProfile');
  //by harry
  Route::post('admin/report','DashboardController@getReport');



});

/*Route::get('/', funcbtion () {
    return view('welcome');
  });*/

     // Route::resource('admin/clienrdetail','clientController');

officemgmt/app/CashOut.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CashOut extends Model
{
    protected $fillable=['expenses_type','amount','paid_by','received_by','payment_mode','date','nepali_date','is_edit','total'];
      public function Report()
   {
   	return $this->hasMany('App\Report');
   }
}

officemgmt/app/Http/Controllers/backend/CashOutController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\CashOut;
use DB;
class CashOutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cashOuts = CashOut::all();
        $data=DB::table("cash_outs")->sum('amount');
        return view('officio.cashout.index',compact('cashOuts','data'))->with('title','Cash Out');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\ResponseC
     */
    public function create()
    {
        return view('officio.cashout.create')->with('title','Create Cash Out');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
        $this->validate($request, [
            'expenses_type' => 'required',
            'amount' => 'required',
            'paid_by' => 'required',
            'received_by' => 'required',
            'payment_mode' => 'required',
           
        ]);
        $input = $request->all();
        if ($input) {
            CashOut::create($input);
            session()->flash('message', 'Cash Out Created.');
            return redirect('admin/cash_out');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cashOut = CashOut::find($id);
        return view('officio.cashout.edit',compact('cashOut'))->with('title','Edit Cash Out');
    }

    /**
     * Update the specified rescashOutource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'expenses_type' => 'required',
            'amount' => 'required',
            'paid_by' => 'required',
            'received_by' => 'required',
            'payment_mode' => 'required',
        ]);
        $cashOut = CashOut::find($id);
        $input = $request->all();
        $cashOut->update($input);
        session()->flash('message', 'Cash Out Updated.');
        return redirect('admin/cash_out');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!request()->ajax()){
            return false;
        }

        CashOut::find($id)->delete();


        session()->flash('message', 'Cash Out Deleted.');

        return response()->json(array(
            'status' => 'success',
        ));
    }
}

officemgmt/resources/views/officio/cashout/create.blade.php
@extends('officio.main')
@section('title','add Cash Out')

@section('content')
{{----}}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create New Cash Out
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
   <div class="row">
    <div class="col-md-12">

        {{--@include('flash.message')--}}
        {{--@include('errors.list')--}}

        <!-- Horizontal Form -->
        <div class="box box-info">
            <!-- form start -->
            <div class="box-body">
                <div class="row">
                  <div class="col-md-8">
                    {{ Form::open(['url'=>'admin/cash_out', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
                    @include('officio.cashout.form')
                    <div class="text-right border-top">
                        <button type="submit" class="btn btn-warning">Create</button>
                    </div>
                    {{ form::close() }}
                </div>
            </div>
        </div>
    </div><!-- /.box -->


</div>
</section>
@stop

officemgmt/resources/views/officio/cashout/edit.blade.php
@extends('officio.main')
@section('title','edit Cash Out')

@section('content')
{{----}}
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Cash Out
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($cashOut, [
        'route' => ['cash_out.update', $cashOut->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
            @include('officio.cashout.form')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

officemgmt/resources/views/officio/cashout/form.blade.php
<div class="box-body">
    <div class="form-group" {{ $errors->has('expenses_type') ? ' has-error' : '' }}>
        <label for="expenses_type" class="col-sm-2 control-label">expenses_type:<span class=help-block"
            style="color: #b30000">&nbsp;* </span></label>

            <div class="col-sm-8">

    <select name="expenses_type" class="form-control">
                                        <option value="Rent">Rent</option>
                                        <option value="Electricity & Garbage">Electricity & Garbage</option>
                                        <option value="Internet">Internet</option>
                                        <option value="Book Printing">Book Printing</option>
                                        <option value="Advertising & Marketing">Advertising & Marketing</option>
                                        <option value="Cancellation/Refund">Cancellation/Refund</option>
                                        <option value="Telephone">Telephone</option>
                                        <option value="Stationery">Stationery</option>
                                        <option value="Lunch">Lunch</option>
                                        <option value="Snacks & tea">Snacks & tea</option>
                                        <option value="Staff Salary">Staff Salary</option>
                                        <option value="Fuel & travel expenses">Fuel & travel expenses</option>
                                        <option value="Repair & maintenance">Repair & maintenance</option>
                                        <option value="Loan Payment">Loan Payment</option>
                                        <option value="Basic Life Support">Basic Life Support</option>
                                        <option value="Others">Others</option>
                                        
                                    </select>
                @if ($errors->has('expenses_type'))
                <span class="help-block">
                    <strong> {{ $errors->first('expenses_type') }}</strong>
                </span>
                @endif

            </div>
        </div>

        <div class="form-group" {{ $errors->has('date') ? ' has-error' : '' }}>
            <label for="date" class="col-sm-2 control-label">date:<span class=help-block"
                style="color: #b30000">&nbsp;* </span></label>

                <div class="col-sm-8">
                    {!! Form::date('date', null , ['class'=> 'form-control', 'placeholder' => ' date', 'id'=>"date"]) !!}

                    @if ($errors->has('date'))
                    <span class="help-block">
                        <strong> {{ $errors->first('date') }}</strong>
                    </span>
                    @endif

                </div>
            </div>
            <div class="form-group" {{ $errors->has('amount') ? ' has-error' : '' }}>
                <label for="amount" class="col-sm-2 control-label">amount:<span class=help-block"
                    style="color: #b30000">&nbsp;* </span></label>

                    <div class="col-sm-8">
                        {!! Form::text('amount', null , ['class'=> 'form-control', 'placeholder' => ' amount', 'id'=>"amount"]) !!}

                        @if ($errors->has('amount'))
                        <span class="help-block">
                            <strong> {{ $errors->first('amount') }}</strong>
                        </span>
                        @endif

                    </div>
                </div>
                
                <div class="form-group" {{ $errors->has('paid_by') ? ' has-error' : '' }}>
                    <label for="paid_by" class="col-sm-2 control-label">paid_by:<span class=help-block"
                        style="color: #b30000">&nbsp;* </span></label>

                        <div class="col-sm-8">
                            {!! Form::text('paid_by', null , ['class'=> 'form-control', 'placeholder' => ' paid_by', 'id'=>"paid_by"]) !!}

                            @if ($errors->has('paid_by'))
                            <span class="help-block">
                                <strong> {{ $errors->first('paid_by') }}</strong>
                            </span>
                            @endif

                        </div>
                    </div>
                    
                    <div class="form-group" {{ $errors->has('received_by') ? ' has-error' : '' }}>
                        <label for="received_by" class="col-sm-2 control-label">received_by:<span class=help-block"
                            style="color: #b30000">&nbsp;* </span></label>

                            <div class="col-sm-8">
                                {!! Form::text('received_by', null , ['class'=> 'form-control', 'placeholder' => ' received_by', 'id'=>"received_by"]) !!}

                                @if ($errors->has('received_by'))
                                <span class="help-block">
                                    <strong> {{ $errors->first('received_by') }}</strong>
                                </span>
                                @endif

                            </div>
                        </div>
                        
                        <div class="form-group" {{ $errors->has('payment_mode') ? ' has-error' : '' }}>
                            <label for="payment_mode" class="col-sm-2 control-label">payment_mode:<span class=help-block"
                                style="color: #b30000">&nbsp;* </span></label>

                                <div class="col-sm-8">
                                 <!--  {!! Form::select('payment_mode' ,['c'=>'cash','ch'=>'cheque','b'=>'bank'],null , ['class'=> 'form-control', 'placeholder' => 'payment_mode', 'id'=>"payment_mode"]) !!} -->
    <select name="payment_mode" class="form-control">
                                        <option value="cash">cash</option>
                                        <option value="cheque">cheque</option>
                                        <option value="bank">bank</option>
                                    </select>
                                  @if ($errors->has('payment_mode'))
                                  <span class="help-block">
                                    <strong> {{ $errors->first('payment_mode') }}</strong>
                                </span>
                                @endif

                            </div>
                        </div>
                        
                        

                        @if(Request::segment(4) == 'edit')
                        <div class="form-group">
                            <label for="status" class="col-sm-2 control-label">Status<span class=help-block" style="color: #b30000">&nbsp;* </span></label>

                            <div class="col-sm-8">

                                <label class="radio-inline"><input type="radio" id="active" name="status" value=1
                                 @if($cashOut->status==1) checked @endif >Active</label>&nbsp;
                                 <label class="radio-inline"><input type="radio" id="inactive" name="status" value=0
                                     @if($cashOut->status==0) checked @endif >Inactive</label>
                                 </div>
                             </div>
                             @endif
                         </div>

officemgmt/resources/views/officio/cashout/index.blade.php
@extends('officio.main')
@section('title','Cash Out')
@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cash Out
         <span>
                <a href="{{ url('admin/cash_out/create') }}">
                    <button type="button" class="btn btn-primary" id="viewbtn">
                        Create Cash Out
                    </button>
                </a>
        </span>
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Expenses Type</th>
                                <th>Date</th>
                                <th>Amount</th>
                                <th>Paid By</th>
                                <th>Recived By</th>
                                <th>Payment Mode</th>
                       
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                $i=1;
                              


                            ?>
                            @foreach($cashOuts as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $type->expenses_type }}</td>
                                    <td>{{ $type->date }}</td>
                                    <td>{{ $type->amount }}</td>
                                    <td>{{ $type->paid_by }}</td>
                                    <td>{{ $type->received_by}}</td>
                                    <td>{{ $type->payment_mode }}</td>
                                
                                        
                                   
                                
                                  
                                    <td>
                                        @if($type->status == 1)
                                            Active
                                        @else
                                            InActive
                                        @endif
                                    </td>

                                    <td>

                                        <a type="button" type="button" class="btn btn-primary btn-sm"
                                                href="{{ route('cash_out.edit', array($type->id)) }}">
                                            <i class="flaticon-edit"></i>
                                        </a>

                                        <form action="{{ route('cash_out.destroy', array($type->id)) }}"
                                              method="DELETE" class="delete-user-form">
                                            {!! csrf_field() !!}

                                            <button type="submit" class="btn btn-sm btn-danger">
                                                <i class="flaticon-delete-button"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
</tbody>
<td>Total &nbsp &nbsp 
<?php echo $total=$data;  ?>
</td>
                        </table>
                    </div>
                </div><!-- /.box-body
            </div><!-- /.box -->
        </div><!-- /.col -->

    </div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop