officemgmt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['namespace'=>'backend'],function(){
  Route::get('/', 'DashboardController@getLogin');

  Route::get('admin', 'DashboardController@getLogin');
  Route::post('admin', 'DashboardController@postLogin');
  Route::get('admin/logout', 'DashboardController@getLogout');

  Route::get('admin/{user_id}/dashboard','DashboardController@index');
  Route::get('admin/dashboard','DashboardController@index');
  Route::resource('admin/user','UserController');
  
  Route::resource('admin/user','UserController');
  Route::post('admin/json','JsonController@json');
  Route::resource('admin/service_charge','ServiceChargeController');


  Route::resource('admin/cash_in','cash_inController');

  Route::resource('admin/cash_out','CashOutController');

  Route::resource('admin/DHA','DHAController');
  Route::resource('admin/enquiry','EnquiryController');
  Route::resource('admin/enquirybythem','EnquiryByThemController');
  Route::resource('admin/enquiryinoffice','EnquiryInOFficeController');
  Route::resource('admin/invoice','InvoiceController');
  Route::resource('admin/reminder','ReminderController');
  Route::resource('admin/service','ServiceController');
  Route::resource('admin/student','StudentController');
  Route::resource('admin/transaction','TransactionController');
  Route::resource('admin/offer','OfferController');
  Route::resource('admin/status','StatusController');
  Route::get('admin/dhastatus','StatusController@createdhastatus');
  Route::post('admin/dhastatus','StatusController@postdhastatus');
  Route::resource('admin/dataflow','DataFlowStatusController');
  Route::get('admin/dataflowform','DataFlowStatusController@create');
  Route::post('admin/dataflowform','DataFlowStatusController@store');
  Route::post('admin/contact','OfferController@postOffer');

  Route::resource('admin/examstatus','ExamStatusController');
  Route::get('admin/examstatusform','ExamStatusController@create');
  Route::post('admin/examstatusform','ExamStatusController@store');
    // newsletter
  Route::get('admin/news','NewsLetterController@contact');
  Route::post('admin/news','NewsLetterController@postcontact');
    // CMS
  Route::get('admin/cms','cmsController@index');
  Route::get('updatePassword', 'DashboardController@updatePassword');   
  Route::get('admin/{username}/profile', 'DashboardController@profile');        
  Route::post('/profilepost', 'DashboardController@updatePassword')->name('profilepost');
  Route::post('/profilepost/{id}', 'DashboardController@editInfo');
  Route::post('updateProfile','DashboardController@updateProfile');
  //by harry
  Route::post('admin/report','DashboardController@getReport');



});

/*Route::get('/', funcbtion () {
    return view('welcome');
  });*/

     // Route::resource('admin/clienrdetail','clientController');

officemgmt/app/ServiceCharge.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceCharge extends Model
{
  protected $fillable=['id','name','qualification','applied_for','service_charge','total'];
    public function Report()
   {
   	return $this->hasMany('App\Report');
   }
   public function invoice(){
   	return $this->hasMany('App\invoice');
   }
}

officemgmt/app/Http/Controllers/backend/ServiceChargeController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ServiceCharge;
use DB;
class ServiceChargeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $serviceCharges = ServiceCharge::all();
        $data=DB::table("service_charges")->sum('service_charge');
        return view('officio.servicecharge.index',compact('serviceCharges','data'))->with('title','Service Charge');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\ResponseC
     */
    public function create()
    {
        return view('officio.servicecharge.create')->with('title','Create Service Charge');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'qualification' => 'required',
            'applied_for' => 'required',
            'service_charge' => 'required',
           
        ]);
        $input = $request->all();
        if ($input) {
           ServiceCharge::create($input);
            session()->flash('message', 'Service  Created.');
            return redirect('admin/service_charge');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $serviceCharge= ServiceCharge::find($id);
        return view('officio.cashout.edit',compact('cashOut'))->with('title','Edit Cash Out');
    }

    /**
     * Update the specified rescashOutource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'name' => 'required',
            'qualification' => 'required',
            'applied_for' => 'required',
            'service_charge' => 'required',
        ]);
        $serviceCharge = ServiceCharge::find($id);
        $input = $request->all();
        $serviceCharge->update($input);
        session()->flash('message', 'Service Charge Updated.');
        return redirect('admin/service_charge');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!request()->ajax()){
            return false;
        }

        ServiceCharge::find($id)->delete();


        session()->flash('message', 'Service Charge Deleted.');

        return response()->json(array(
            'status' => 'success',
        ));
    }
}

officemgmt/resources/views/officio/servicecharge/create.blade.php
@extends('officio.main')
@section('title','add Service Charge')

@section('content')
{{----}}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create New Service  Charge
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
   <div class="row">
    <div class="col-md-12">

        {{--@include('flash.message')--}}
        {{--@include('errors.list')--}}

        <!-- Horizontal Form -->
        <div class="box box-info">
            <!-- form start -->
            <div class="box-body">
                <div class="row">
                  <div class="col-md-8">
                    {{ Form::open(['url'=>'admin/service_charge', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
                    @include('officio.servicecharge.form')
                    <div class="text-right border-top">
                        <button type="submit" class="btn btn-warning">Create</button>
                    </div>
                    {{ form::close() }}
                </div>
            </div>
        </div>
    </div><!-- /.box -->


</div>
</section>
@stop

officemgmt/resources/views/officio/servicecharge/edit.blade.php
@extends('officio.main')
@section('title','edit Service Charge')

@section('content')
{{----}}
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Service Charge
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($serviceCharge, [
        'route' => ['service_charge.update', $serviceCharge->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
            @include('officio.servicecharge.form')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

officemgmt/resources/views/officio/servicecharge/form.blade.php
<div class="box-body">
     <div class="form-group" {{ $errors->has('name') ? ' has-error' : '' }}>
        <label for="name" class="col-sm-2 control-label">name:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
            {!! Form::text('name', null , ['class'=> 'form-control', 'placeholder' => ' name', 'id'=>"name"]) !!}

            @if ($errors->has('name'))
                <span class="help-block">
                    <strong> {{ $errors->first('name') }}</strong>
                </span>
            @endif

        </div>
    </div>

       <div class="form-group" {{ $errors->has('qualification') ? ' has-error' : '' }}>
                        <label for="qualification" class="col-sm-2 control-label">qualification:<span class=help-block"
                            style="color: #b30000">&nbsp;* </span></label>

                            <div class="col-sm-8">
                                {!! Form::text('qualification', null , ['class'=> 'form-control', 'placeholder' => ' qualification', 'id'=>"qualification"]) !!}

                                @if ($errors->has('qualification'))
                                <span class="help-block">
                                    <strong> {{ $errors->first('qualification') }}</strong>
                                </span>
                                @endif

                            </div>
                        </div>
    <div class="form-group" {{ $errors->has('applied_for') ? ' has-error' : '' }}>
        <label for="applied_for" class="col-sm-2 control-label">applied_for:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
            {!! Form::text('applied_for', null , ['class'=> 'form-control', 'placeholder' => ' applied_for', 'id'=>"applied_for"]) !!}

            @if ($errors->has('applied_for'))
                <span class="help-block">
                    <strong> {{ $errors->first('applied_for') }}</strong>
                </span>
            @endif

        </div>
    </div>
   
    <div class="form-group" {{ $errors->has('service_charge') ? ' has-error' : '' }}>
        <label for="service_charge" class="col-sm-2 control-label">service_charge:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
            {!! Form::text('service_charge', null , ['class'=> 'form-control', 'placeholder' => ' service_charge', 'id'=>"service_charge"]) !!}

            @if ($errors->has('service_charge'))
                <span class="help-block">
                    <strong> {{ $errors->first('service_charge') }}</strong>
                </span>
            @endif

        </div>
    </div>
  


  

    @if(Request::segment(4) == 'edit')
        <div class="form-group">
            <label for="status" class="col-sm-2 control-label">Status<span class=help-block" style="color: #b30000">&nbsp;* </span></label>

            <div class="col-sm-8">

                <label class="radio-inline"><input type="radio" id="active" name="status" value=1
                                                   @if($serviceCharge->status==1) checked @endif >Active</label>&nbsp;
                <label class="radio-inline"><input type="radio" id="inactive" name="status" value=0
                                                   @if($serviceCharge->status==0) checked @endif >Inactive</label>
            </div>
        </div>
    @endif
</div>

officemgmt/resources/views/officio/servicecharge/index.blade.php
@extends('officio.main')
@section('title','Cash Out')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>

       <span>
        <a href="{{ url('admin/cash_out/create') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
                Create Service Charge
            </button>
        </a>
    </span>
</h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name>
                                    <th>Qualification</th>
                                    <th>Applied for</th>
                                    <th>Service charge</th>


                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i=1;
                                ?>
                                @foreach($serviceCharges as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $type->name }}</td>
                                    <td>{{ $type->qualification}}</td>
                                    <td>{{ $type->applied_for }}</td>
                                    <td>{{ $type->service_charge }}</td>


                                    <td>
                                        @if($type->status == 1)
                                        Active
                                        @else
                                        InActive
                                        @endif
                                    </td>

                                    <td>

                                        <a type="button" type="button" class="btn btn-primary btn-sm"
                                        href="{{ route('service_charge.edit', array($type->id)) }}">
                                        <i class="flaticon-edit"></i>
                                    </a>

                                    <form action="{{ route('service_charge.destroy', array($type->id)) }}"
                                      method="DELETE" class="delete-user-form">
                                      {!! csrf_field() !!}

                                      <button type="submit" class="btn btn-sm btn-danger">
                                        <i class="flaticon-delete-button"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        </tbody>
                        @endforeach


                        <td>Total &nbsp &nbsp 
                            <?php echo $total=$data;  ?>
                        </td>

                    </table>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->

</div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop