officemgmt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['namespace'=>'backend'],function(){
  Route::get('/', 'DashboardController@getLogin');

  Route::get('admin', 'DashboardController@getLogin');
  Route::post('admin', 'DashboardController@postLogin');
  Route::get('admin/logout', 'DashboardController@getLogout');

  Route::get('admin/{user_id}/dashboard','DashboardController@index');
  Route::get('admin/dashboard','DashboardController@index');
  Route::resource('admin/user','UserController');
  
  Route::resource('admin/user','UserController');
  Route::post('admin/json','JsonController@json');
  Route::resource('admin/service_charge','ServiceChargeController');


  Route::resource('admin/cash_in','cash_inController');

  Route::resource('admin/cash_out','CashOutController');

  Route::resource('admin/DHA','DHAController');
  Route::resource('admin/enquiry','EnquiryController');
  Route::resource('admin/enquirybythem','EnquiryByThemController');
  Route::resource('admin/enquiryinoffice','EnquiryInOFficeController');
  Route::resource('admin/invoice','InvoiceController');
  Route::resource('admin/reminder','ReminderController');
  Route::resource('admin/service','ServiceController');
  Route::resource('admin/student','StudentController');
  Route::resource('admin/transaction','TransactionController');
  Route::resource('admin/offer','OfferController');
  Route::resource('admin/status','StatusController');
  Route::get('admin/dhastatus','StatusController@createdhastatus');
  Route::post('admin/dhastatus','StatusController@postdhastatus');
  Route::resource('admin/dataflow','DataFlowStatusController');
  Route::get('admin/dataflowform','DataFlowStatusController@create');
  Route::post('admin/dataflowform','DataFlowStatusController@store');
  Route::post('admin/contact','OfferController@postOffer');

  Route::resource('admin/examstatus','ExamStatusController');
  Route::get('admin/examstatusform','ExamStatusController@create');
  Route::post('admin/examstatusform','ExamStatusController@store');
    // newsletter
  Route::get('admin/news','NewsLetterController@contact');
  Route::post('admin/news','NewsLetterController@postcontact');
    // CMS
  Route::get('admin/cms','cmsController@index');
  Route::get('updatePassword', 'DashboardController@updatePassword');   
  Route::get('admin/{username}/profile', 'DashboardController@profile');        
  Route::post('/profilepost', 'DashboardController@updatePassword')->name('profilepost');
  Route::post('/profilepost/{id}', 'DashboardController@editInfo');
  Route::post('updateProfile','DashboardController@updateProfile');
  //by harry
  Route::post('admin/report','DashboardController@getReport');



});

/*Route::get('/', funcbtion () {
    return view('welcome');
  });*/

     // Route::resource('admin/clienrdetail','clientController');

officemgmt/app/Cash_in.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cash_in extends Model
{
    protected $fillable=['service_type','service_charge','paid_by','received_by','payment_mode','date','nepali_date','is_edit','total'];
      

   public function Report()
   {
   	return $this->hasMany('App\Report');
   }

}

officemgmt/app/Http/Controllers/backend/cash_inController.php
<?php
namespace App\Http\Controllers\backend;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Cash_in;
use DB;
use App\Report;
use Validator;
class cash_inController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cashIn = Cash_in::all();
        $data = DB::table("cash_ins")->sum('service_charge');


        return view('officio.cashin.index',compact('cashIn','data'))->with('title','Cash in');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('officio.cashin.create')->with('title','Create Cash in');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $this->validate($request, [
            'service_type' => 'required',
            'service_charge' => 'required',


            // 'date' => 'required',

            'paid_by' => 'required',
            'received_by' => 'required',



        ]);
        $input = $request->all();
        $cashins=Cash_in::pluck('service_charge','id');
        if ($input) {

         $cash_entered=Cash_in::create($input);
         

            session()->flash('message', 'Cash in Created.');
            return redirect('admin/cash_in');
        }
          $reports= Report::create([
                    'cashin_id' =>$ca,
                    // 'client_id'=>$clients->id,
                    // 'action'=>'New Client'.' '.$request->name.' '.'Created.',
                ]);
    }


//     public function store(Request $request){

//         $input = $request->all();
//         $rules = [

//         'service_type' => 'required',
//         'service_charge' => 'required',


//         'date' => 'required',
//         'payment_mode' => 'required',

//         'paid_by' => 'required',
//         'received_by' => 'required',
//         ];

//         $validate = Validator::make($request->all(),$rules);

//         if($validate->fails()){

//             return redirect('admin/cash_in')
//             ->withErrors($validate)
//             ->withInput();
//         }
//         else{
//             // $input['password'] = $request->password ? bcrypt($request->password):bcrypt('default');
//             // $users = User::create($input);
            
//             // $input['user_id'] = $users->id;
//             $cashins = Cash_in::create($input);
//             if($cashins){

//                 // if($request->segment(1)=='admin'){
//                 // // if(Auth::guard('admin')){
//                 //     $staff_id = Null;
//                 // }
//                 // else{
//                 //     $staff_id = Auth::guard('employee')->user()->id;
//                 // }
//                 $track_record = Report::create([
                   
//                     'cashin_id'=>$cashins->service_charge,
                  
//                     ]);
//             }

//             Session()->flash('message','Cash In Added Successfully.');
//             // if(Auth::guard('admin')->user()){
        
//     }
// }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cashIn = Cash_in::find($id);
        return view('officio.cashin.edit',compact('cashIn'))->with('title','Edit Visa Type');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
           'service_type' => 'required',
           'date' => 'required',
           'service_charge' => 'required',
           'paid_by' => 'required',
           'received_by' => 'required',
           'payment_mode' => 'required',



           ]);
        $cashIn = Cash_in::find($id);
        $input = $request->all();
        $cashIn->update($input);
        session()->flash('message', 'Cash In Updated.');
        return redirect('admin/cash_in');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!request()->ajax()){
            return false;
        }

        Cash_in::find($id)->delete();


        session()->flash('message', 'Cash In Deleted.');

        return response()->json(array(
            'status' => 'success',
            ));
    }
}

officemgmt/resources/views/officio/cashin/create.blade.php
@extends('officio.main')
@section('title','add Cash In')

@section('content')
{{----}}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create New Cash In
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    <div class="row">
        <div class="col-md-12">

            {{--@include('flash.message')--}}
            {{--@include('errors.list')--}}

            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <div class="box-body">
                    <div class="row">
                      <div class="col-md-8">
                        {{ Form::open(['url'=>'admin/cash_in', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
                        @include('officio.cashin.form')
                        <div class="text-right border-top">
                            <button type="submit" class="btn btn-warning">Create</button>
                        </div>
                        {{ form::close() }}
                    </div>
                </div>
            </div>
        </div><!-- /.box -->


    </div><!-- /.col -->





</section>
@stop

officemgmt/resources/views/officio/cashin/edit.blade.php
@extends('officio.main')
@section('title','edit Cash In')

@section('content')
{{----}}
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Cash In
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($cashIn, [
        'route' => ['cash_in.update', $cashIn->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
            @include('officio.cashin.form')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

officemgmt/resources/views/officio/cashin/form.blade.php
<div class="box-body">
	<div class="form-group" {{ $errors->has('service_type') ? ' has-error' : '' }}>
		<label for="service_type" class="col-sm-2 control-label">service_type:<span class=help-block"
			style="color: #b30000">&nbsp;* </span></label>

			<div class="col-sm-8">
				<!--  {!! Form::select('service_type', ['D'=>'DHA MCQ/HAAD MCQ','B'=>'Basic Life Support'],null , ['class'=> 'form-control', 'placeholder' => ' service_type', 'id'=>"service_type"]) !!} -->
				<select name="service_type" class="form-control">
					<option value="DHA MCQ/HAAD MCQ
					">DHA MCQ/HAAD MCQ
				</option>
				<option value="Basic Life Support">Basic Life Support</option>
			</select>
			@if ($errors->has('service_type'))
			<span class="help-block">
				<strong> {{ $errors->first('service_type') }}</strong>
			</span>
			@endif

		</div>
	</div>
	<div class="form-group" {{ $errors->has('date') ? ' has-error' : '' }}>
		<label for="date" class="col-sm-2 control-label">date:<span class=help-block"
			style="color: #b30000">&nbsp;* </span></label>

			<div class="col-sm-8">
				{!! Form::date('date', null , ['class'=> 'form-control', 'placeholder' => ' date', 'id'=>"date"]) !!}

				@if ($errors->has('date'))
				<span class="help-block">
					<strong> {{ $errors->first('date') }}</strong>
				</span>
				@endif

			</div>
		</div>



		<div class="form-group" {{ $errors->has('service_charge') ? ' has-error' : '' }}>
			<label for="service_charge" class="col-sm-2 control-label">service_charge:<span class=help-block"
				style="color: #b30000">&nbsp;* </span></label>

				<div class="col-sm-8">
					{!! Form::text('service_charge', null , ['class'=> 'form-control', 'placeholder' => ' service_charge', 'id'=>"service_charge"]) !!}

					@if ($errors->has('service_charge'))
					<span class="help-block">
						<strong> {{ $errors->first('service_charge') }}</strong>
					</span>
					@endif

				</div>
			</div>


			<div class="form-group" {{ $errors->has('paid_by') ? ' has-error' : '' }}>
				<label for="paid_by" class="col-sm-2 control-label">paid_by:<span class=help-block"
					style="color: #b30000">&nbsp;* </span></label>

					<div class="col-sm-8">
						{!! Form::text('paid_by', null , ['class'=> 'form-control', 'placeholder' => ' paid_by', 'id'=>"paid_by"]) !!}

						@if ($errors->has('paid_by'))
						<span class="help-block">
							<strong> {{ $errors->first('paid_by') }}</strong>
						</span>
						@endif

					</div>
				</div>
				<div class="form-group" {{ $errors->has('received_by') ? ' has-error' : '' }}>
					<label for="received_by" class="col-sm-2 control-label">received_by:<span class=help-block"
						style="color: #b30000">&nbsp;* </span></label>

						<div class="col-sm-8">
							{!! Form::text('received_by', null , ['class'=> 'form-control', 'placeholder' => ' received_by', 'id'=>"received_by"]) !!}

							@if ($errors->has('received_by'))
							<span class="help-block">
								<strong> {{ $errors->first('received_by') }}</strong>
							</span>
							@endif

						</div>
					</div>
					<div class="form-group" {{ $errors->has('payment_mode') ? ' has-error' : '' }}>
						<label for="payment_mode" class="col-sm-2 control-label">payment_mode:<span class=help-block"
							style="color: #b30000">&nbsp;* </span></label>

							<div class="col-sm-8">
								
								<select name="payment_mode" class="form-control">
									<option value="cash">cash</option>
									<option value="cheque">cheque</option>
									<option value="bank">bank</option>
								</select>
								@if ($errors->has('payment_mode'))
								<span class="help-block">
									<strong> {{ $errors->first('payment_mode') }}</strong>
								</span>
								
								@endif

							</div>
						</div>
               <!--      <div class="form-group" {{ $errors->has('date') ? ' has-error' : '' }}>
                        <label for="date" class="col-sm-2 control-label">date:<span class=help-block"
                            style="color: #b30000">&nbsp;* </span></label>

                            <div class="col-sm-8">
                                {!! Form::date('date', null , ['class'=> 'form-control', 'placeholder' => ' date', 'id'=>"date"]) !!}

                                @if ($errors->has('date'))
                                <span class="help-block">
                                    <strong> {{ $errors->first('date') }}</strong>
                                </span>
                                @endif

                            </div>
                        </div> -->
                     <!--    <div class="form-group" {{ $errors->has('nepali_date') ? ' has-error' : '' }}>
                            <label for="nepali_date" class="col-sm-2 control-label">nepali_date:<span class=help-block"
                                style="color: #b30000">&nbsp;* </span></label>

                                <div class="col-sm-8">
                                    {!! Form::date('nepali_date', null , ['class'=> 'form-control', 'placeholder' => ' nepali_date', 'id'=>"nepali_date"]) !!}

                                    @if ($errors->has('nepali_date'))
                                    <span class="help-block">
                                        <strong> {{ $errors->first('nepali_date') }}</strong>
                                    </span>
                                    @endif

                                </div>
                            </div> -->

                         <!--    <div class="form-group" {{ $errors->has('total') ? ' has-error' : '' }}>
                                <label for="total" class="col-sm-2 control-label">Total:<span class=help-block"
                                    style="color: #b30000">&nbsp;* </span></label>

                                    <div class="col-sm-8">
                                        {!! Form::text('total' ,null , ['class'=> 'form-control', 'placeholder' => 'total', 'id'=>"total"]) !!}

                                        @if ($errors->has('total'))
                                        <span class="help-block">
                                            <strong> {{ $errors->first('total') }}</strong>
                                        </span>
                                        @endif

                                    </div>
                                </div> -->
                                @if(Request::segment(4) == 'edit')
                                <div class="form-group">
                                	<label for="status" class="col-sm-2 control-label">Status<span class=help-block" style="color: #b30000">&nbsp;* </span></label>

                                	<div class="col-sm-8">

                                		<label class="radio-inline"><input type="radio" id="active" name="status" value=1
                                			@if($cashIn->status==1) checked @endif >Active</label>&nbsp;
                                			<label class="radio-inline"><input type="radio" id="inactive" name="status" value=0
                                				@if($cashIn->status==0) checked @endif >Inactive</label>
                                			</div>
                                		</div>
                                		@endif
                                	</div>

officemgmt/resources/views/officio/cashin/index.blade.php
    @extends('officio.main')
    @section('title','Cash In')
    @section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>

           <span>
            <a href="{{ url('admin/cash_in/create') }}">
                <button type="button" class="btn btn-success" id="viewbtn">
                    Create Cash In
                </button>
            </a>
        </span>
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>service_type</th>
                                    <th>date</th>

                                    <th>service_charge</th>
                                    <th>paid_by</th>

                                    <th>received_by</th>
                                    <th>payment_mode</th>
                                    <th>Total</th>

                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i=1;
                                ?>
                                @foreach($cashIn as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $type->service_type }}</td>
                                    <td>{{ $type->date }}</td>
                                    <td>{{ $type->service_charge}}</td>
                                    <td>{{ $type->paid_by }}</td>
                                    <td>{{ $type->received_by }}</td>
                                    <td>{{ $type->payment_mode }}</td>
                                    <td><?php  $total=0;  ?>
                                        {{ $type->total=$total + $type->service_charge}}</td>



                                        <td>
                                            @if($type->status == 1)
                                            Active
                                            @else
                                            InActive
                                            @endif
                                        </td>

                                        <td>

                                            <a type="button" type="button" class="btn btn-primary btn-sm"
                                            href="{{ route('cash_in.edit', array($type->id)) }}">
                                            <i class="flaticon-edit"></i>
                                        </a>

                                        <form action="{{ route('cash_in.destroy', array($type->id)) }}"
                                          method="DELETE" class="delete-user-form">
                                          {!! csrf_field() !!}

                                          <button type="submit" class="btn btn-sm btn-danger">
                                            <i class="flaticon-delete-button"></i>
                                        </button>
                                    </form>
                                </td>
                                
                            </tr>
                        </tbody>
                        @endforeach

                        <td>Total &nbsp &nbsp 
                            <?php echo $total=$data;  ?>
                        </td>

                    </table>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->

</div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop