officemgmt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['namespace'=>'backend'],function(){
  Route::get('/', 'DashboardController@getLogin');

  Route::get('admin', 'DashboardController@getLogin');
  Route::post('admin', 'DashboardController@postLogin');
  Route::get('admin/logout', 'DashboardController@getLogout');

  Route::get('admin/{user_id}/dashboard','DashboardController@index');
  Route::get('admin/dashboard','DashboardController@index');
  Route::resource('admin/user','UserController');
  
  Route::resource('admin/user','UserController');
  Route::post('admin/json','JsonController@json');
  Route::resource('admin/service_charge','ServiceChargeController');


  Route::resource('admin/cash_in','cash_inController');

  Route::resource('admin/cash_out','CashOutController');

  Route::resource('admin/DHA','DHAController');
  Route::resource('admin/enquiry','EnquiryController');
  Route::resource('admin/enquirybythem','EnquiryByThemController');
  Route::resource('admin/enquiryinoffice','EnquiryInOFficeController');
  Route::resource('admin/invoice','InvoiceController');
  Route::resource('admin/reminder','ReminderController');
  Route::resource('admin/service','ServiceController');
  Route::resource('admin/student','StudentController');
  Route::resource('admin/transaction','TransactionController');
  Route::resource('admin/offer','OfferController');
  Route::resource('admin/status','StatusController');
  Route::get('admin/dhastatus','StatusController@createdhastatus');
  Route::post('admin/dhastatus','StatusController@postdhastatus');
  Route::resource('admin/dataflow','DataFlowStatusController');
  Route::get('admin/dataflowform','DataFlowStatusController@create');
  Route::post('admin/dataflowform','DataFlowStatusController@store');
  Route::post('admin/contact','OfferController@postOffer');

  Route::resource('admin/examstatus','ExamStatusController');
  Route::get('admin/examstatusform','ExamStatusController@create');
  Route::post('admin/examstatusform','ExamStatusController@store');
    // newsletter
  Route::get('admin/news','NewsLetterController@contact');
  Route::post('admin/news','NewsLetterController@postcontact');
    // CMS
  Route::get('admin/cms','cmsController@index');
  Route::get('updatePassword', 'DashboardController@updatePassword');   
  Route::get('admin/{username}/profile', 'DashboardController@profile');        
  Route::post('/profilepost', 'DashboardController@updatePassword')->name('profilepost');
  Route::post('/profilepost/{id}', 'DashboardController@editInfo');
  Route::post('updateProfile','DashboardController@updateProfile');
  //by harry
  Route::post('admin/report','DashboardController@getReport');



});

/*Route::get('/', funcbtion () {
    return view('welcome');
  });*/

     // Route::resource('admin/clienrdetail','clientController');

officemgmt/app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $fillable=['name','title','description','percentage','image','email','first_name','last_name'];
}

officemgmt/app/Http/Controllers/backend/OfferController.php
<?php
namespace App\Http\Controllers\backend;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Offer;
use App\User;
use Validator;
use Redirect;
use Auth;
use Mail;
// use Request;
use session;

class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offers = Offer::all();
        
        return view('officio.offer.index',compact('offers'))->with('title','Griffith offer');
    }
    /**Griffith 
     * Show the form for creating a new resource.
     *ResponseC
     * @return \Illuminate\Http\
     */
    public function create()
    {
        return view('officio.offer.create')->with('title','Create Griffith offer');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [

            'name' => 'required',
            'title' => 'required',
            'description' => 'required',
            'address' => 'required',
            'percentage' => 'required',
            'image' => 'required',
            'email' => 'required',
            
            
            
            ]);
        $input = $request->all();
        if ($input) {
            Offer::create($input);
            session()->flash('message', 'Griffith offer Created.');
            return redirect('admin/offer');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $offers=Offer::find($id);
     $offers=Offer::all();
     // $users=Auth::user()->id;
     $users=User::all();
     return view('officio.offer.show',compact('offers','users'))->with('title','Griffith offer');
 }


 public function postOffer(Request $request){


     $data = $request->all();

       $data1 = $request->input('email');
 

        $check = Validator::make($data, array(

                 'first_name' => 'required',
        'last_name' => 'required',
        'email' => 'required',
        ));

        // $emails = [

        //     'palistha01@gmail.com'
        // ];

        // if the validator fails, redirect back to the form
        if ($check->fails()) {
            return Redirect::back()
                            ->withErrors($check) // send back all errors to the login form
                            ->withInput();
        } else {
            Mail::send('emails.contact', ['data' => $data], function ($message) use ($data,$data1){
                    
                $message->to($data1)->subject('Contact query');
              
            });
            $request->session()->flash('success', 'Contact request has been sent.');
            return redirect('admin/offer');
        }


                          
                        }


 // public function postoffer(){
 //    $data = Request::all();
 //       // var_dump( $data); die;
 //    $data1 = Request::input('email');
 //    // $checkboxes2 = Request::get('formemail');
 //    // $checkboxes3 = Request::get('inemail');
 // // dd($checkboxes1);
 //    $check = Validator::make($data, array(

 //        'first_name' => 'required',
 //        'last_name' => 'required',
 //        'email' => 'required',
 //        ));

 //    $emails = [

 //    'palistha01@gmail.com'
 //    ];

 //        // if the validator fails, redirect back to the form
 //    if ($check->fails()) {
 //        return Redirect::back()
 //                            ->withErrors($check) // send back all errors to the login form
 //                            ->withInput();
 //                        } else {
 //                           //  foreach ($data1 as $checkEmail1) {
 //                           //     $this->sendEmail($checkEmail1,$data);
 //                           // } 
                         


 //                           Request::session()->flash('success', 'Contact request has been sent.');
 //                           return redirect('admin/offer');
 //                       }


 //                   }
 //                   private function sendEmail($email_address,$data){
 //                    Mail::send('emails.contact', ['data' => $data], function ($message) use ($data,$email_address){
 //                       // $message->to( $request->input('usemail') );
 //                        $message->to($email_address)->subject('Contact query');
 //                    });
 //                }  
                public function edit($id)
                {
                    $offer = Offer::find($id);
                    return view('officio.offer.edit',compact('offer'))->with('title','Edit Griffith offer');
                }

    /**
     * Update the specified rescashOutource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'name' => 'required',
          'title' => 'required',
          'description' => 'required',
          'address' => 'required',
          'percentage' => 'required',
          'image' => 'required',
          'email' => 'required'
          
          ]);
        $offer = Offer::find($id);
        $input = $request->all();
        $offer->update($input);
        session()->flash('message', 'Griffith offer Updated.');
        return redirect('admin/offer');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!request()->ajax()){
            return false;
        }

        Offer::find($id)->delete();


        session()->flash('message', 'Griffith offer Deleted.');

        return response()->json(array(
            'status' => 'success',
            ));
    }
}

officemgmt/resources/views/officio/offer/create.blade.php
@extends('officio.main')
@section('title','add Griffith offer')
offer
@section('content')
{{----}}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create New Griffith offer
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
   <div class="row">
    <div class="col-md-12">

        {{--@include('flash.message')--}}
        {{--@include('errors.list')--}}

        <!-- Horizontal Form -->
        <div class="box box-info">
            <!-- form start -->
            <div class="box-body">
                <div class="row">
                  <div class="col-md-8">
                    {{ Form::open(['url'=>'admin/offer', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
                    @include('officio.offer.form')
                    <div class="text-right border-top">
                        <button type="submit" class="btn btn-warning">Create</button>
                    </div>
                    {{ form::close() }}
                </div>
            </div>
        </div>
    </div><!-- /.box -->


</div>
</section>
@stop

officemgmt/resources/views/officio/offer/edit.blade.php
@extends('officio.main')
@section('title','edit Griffith offer')

@section('content')
{{----}}
        <!-- Content Header (Pag header) -->
<section class="content-header">
    <h1>
        Edit Griffith offer
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($offer, [
        'route' => ['offer.update', $offer->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
            @include('officio.offer.form')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

officemgmt/resources/views/officio/offer/form.blade.php
<div class="box-body">

    
    <div class="form-group" {{ $errors->has('name') ? ' has-error' : '' }}>
        <label for="name" class="col-sm-2 control-label">name:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
          {!! Form::text('name', null , ['class'=> 'form-control', 'placeholder' => ' name', 'id'=>"name"]) !!}

            @if ($errors->has('name'))
                <span class="help-block">
                    <strong> {{ $errors->first('name') }}</strong>
                </span>
            @endif

        </div>
    </div>

        <div class="form-group" {{ $errors->has('title') ? ' has-error' : '' }}>
            <label for="title" class="col-sm-2 control-label">title:<span class=help-block"
                style="color: #b30000">&nbsp;* </span></label>

                <div class="col-sm-8">
                    {!! Form::text('title', null , ['class'=> 'form-control', 'placeholder' => ' title', 'id'=>"title"]) !!}

                    @if ($errors->has('title'))
                    <span class="help-block">
                        <strong> {{ $errors->first('title') }}</strong>
                    </span>
                    @endif

                </div>
            </div>
    <div class="form-group" {{ $errors->has('description') ? ' has-error' : '' }}>
        <label for="description" class="col-sm-2 control-label">description:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
           <textarea class="form-control ckeditor" name="description"  id="description" >
               </textarea>

            @if ($errors->has('description'))
                <span class="help-block">
                    <strong> {{ $errors->first('description') }}</strong>
                </span>
            @endif

        </div>
    </div>
    <div class="form-group" {{ $errors->has('address') ? ' has-error' : '' }}>
        <label for="address" class="col-sm-2 control-label">address:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
          {!! Form::text('address', null , ['class'=> 'form-control', 'placeholder' => ' address', 'id'=>"address"]) !!}

            @if ($errors->has('address'))
                <span class="help-block">
                    <strong> {{ $errors->first('address') }}</strong>
                </span>
            @endif

        </div>
    </div>
    
    <div class="form-group" {{ $errors->has('percentage') ? ' has-error' : '' }}>
        <label for="percentage" class="col-sm-2 control-label">percentage:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
          {!! Form::text('percentage', null , ['class'=> 'form-control', 'placeholder' => ' percentage', 'id'=>"percentage"]) !!}

            @if ($errors->has('percentage'))
                <span class="help-block">
                    <strong> {{ $errors->first('percentage') }}</strong>
                </span>
            @endif

        </div>
    </div>
     <div class="form-group" {{ $errors->has('image') ? ' has-error' : '' }}>
        <label for="image" class="col-sm-2 control-label">image:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
          <!--  <textarea class="form-control ckeditor" name="image"  id="image" >
               </textarea >-->
 {{ Form::textarea('image',null,['class'=>'form-control ckeditor','placeholder'=>'Enter image ']) }}
            @if ($errors->has('image'))
                <span class="help-block">
                    <strong> {{ $errors->first('image') }}</strong>
                </span>
            @endif

        </div>
    </div>
     <div class="form-group" {{ $errors->has('email') ? ' has-error' : '' }}>
        <label for="email" class="col-sm-2 control-label">email:<span class=help-block"
                                                                    style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-8">
          {!! Form::text('email', null , ['class'=> 'form-control', 'placeholder' => ' email', 'id'=>"email"]) !!}

            @if ($errors->has('email'))
                <span class="help-block">
                    <strong> {{ $errors->first('email') }}</strong>
                </span>
            @endif

        </div>
    </div>
      
    @if(Request::segment(4) == 'edit')
        <div class="form-group">
            <label for="status" class="col-sm-2 control-label">Status<span class=help-block" style="color: #b30000">&nbsp;* </span></label>

            <div class="col-sm-8">

                <label class="radio-inline"><input type="radio" id="active" name="status" value=1
                                                   @if($offer->status==1) checked @endif >Active</label>&nbsp;
                <label class="radio-inline"><input type="radio" id="inactive" name="status" value=0
                                                   @if($offer->status==0) checked @endif >Inactive</label>
            </div>
        </div>
    @endif
</div>

officemgmt/resources/views/officio/offer/index.blade.php
@extends('officio.main')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>

       <span>
        <a href="{{ url('admin/offer/create') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
                Create Griffith offer
            </button>
        </a>
    </span>
</h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                                <tr>
                                    <th>#</th>

                                    <th>Name</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Percentage</th>
                                    <th>Images</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i=1;
                                ?>
                                @foreach($offers as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>


                                    <td>{{ $type->name }}</td>
                                    <td>{{ $type->title}}</td>
                                    <td><?php echo $type->description; ?></td>
                                    <td>{{ $type->percentage}}</td>
                                    <td><?php echo $type->image; ?></td>
                                    <td>{{ $type->email}}</td>




                                    <td>
                                        @if($type->status == 1)
                                        Active
                                        @else
                                        InActive
                                        @endif
                                    </td>

                                    <td>

                                        <a type="button" type="button" class="btn btn-primary btn-sm"
                                        href="{{ route('offer.edit', array($type->id)) }}">
                                        <i class="flaticon-edit"></i>
                                    </a>

                                    <form action="{{ route('offer.destroy', array($type->id)) }}"
                                      method="DELETE" class="delete-user-form">
                                      {!! csrf_field() !!}

                                      <button type="submit" class="btn btn-sm btn-danger">
                                        <i class="flaticon-delete-button"></i>
                                    </button>

                                </form>
                               
                                      <a  href="{{ route('offer.show', array($type->id)) }}">Show Offer
                                       
                                    </a>
                                </td>
                            </tr>
                        </tbody>

                        @endforeach

                       
                    </table>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->

</div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop

officemgmt/resources/views/officio/offer/show.blade.php
@extends('officio.main')


@section('content')
<!DOCTYPE html>
<html>
<head>
	<title>EID OFFER</title>
	
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style type="text/css">
        .background-color-main 
        {
            background: linear-gradient(270deg, #15632f, #a71c1c, #E7E7E7, #504c4c, #2798d8);
            background-size: 1000% 1000%;
            -webkit-animation: gifback 30s ease infinite;
            -moz-animation: gifback 30s ease infinite;
            -o-animation: gifback 30s ease infinite;
            animation: gifback 30s ease infinite;
        }
        @-webkit-keyframes gifback {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }
        @-moz-keyframes gifback {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }
        @-o-keyframes gifback {
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }
        @keyframes gifback { 
            0%{background-position:0% 50%}
            50%{background-position:100% 50%}
            100%{background-position:0% 50%}
        }

        .eid-special-offer
        {
            text-align: center;
            font-size: 20px;
            color: white;
            font-weight: bold;
        }

        .eid-mubarak
        {
            text-align: center;
            font-size: 24px;
            color: white;
            font-weight: bold;
        }

        .additional-off
        {
            text-align: center;
            font-size: 21px;
            color: white;
            font-weight: bold;
        }

        .details
        {
            font-size: 16px;
            color: white;
            text-align: center;

        }

        .width-img
        {
            width: 570px !important;
        }

        .name
        {
            width: 250px;
            height: 70px;
            padding-left: 5px;
            font-size: 20px;
        }

        .email
        {
            width: 504px;
            margin: 10px 0 10px 0;
            height: 75px;
            padding-left: 5px;
            font-size: 20px;
        }

        .btn-submit
        {
            width: 504px;
            height: 85px;
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            background-color: #3ba160;
            color: white;
        }

        
        .img-form-main
        {
            margin-top: 10px;
        }


    </style>
</head>
<body>

    <?php foreach($offers as $offer){ ?>	
    <div class="container background-color-main">
     <div class="row">
      <div class="col-md-12">
       <div class="eid-special-offer">
        <br><?php echo $offer->title; ?>	
    </div>

    <div class="eid-mubarak">
        <br><?php echo $offer->name; ?>	
    </div>

    <div class="additional-off">
        <p><?php echo $offer->description; ?></p>
    </div>

    <div class="details">
        <p>Use the coupon code below</p><p> when you checkout to get an additional <?php echo $offer->percentage; ?>	 off your purchase and be eligible for future discounts when you join our mailing list.</p>
    </div>
</div>

<div class="col-md-12 img-form-main">
   <div class="col-md-6 width-img">
       <!-- 	<img src="<?php echo $offer->image; ?>" alt="eid-images" width="500px">	 -->			<img src="<?php echo $offer->image; ?>" alt="eid-images" width="500px"> 
   </div>
   <div class="col-md-6">
       
    {{ Form::open(['url'=>'admin/contact', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
    <input type="text" name="first_name" placeholder="First Name" class="name" required/>
    <input type="text" name="last_name" placeholder="Last Name" class="name" required/>
    <input type="hidden" name="toemail" placeholder="Email" value="<?php echo $offer->email;?>" class="email" required/>
    <input type="text" name="email" placeholder="Email" value="<?php echo $offer->email;?>" class="email" required/>
    <p>
        <input type="submit" name="btnSubmit" value="GET MY <?php echo $offer->percentage; ?> OFF!" class="btn-submit"></p>
        
        {{ form::close() }}
    </div>
</div>
</div>
</div>
<?php } ?>
</body>
</html>
@stop